package model.staticvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 13 13:56:55 CEST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StatiYearViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StatiYearViewImpl() {
    }
}

